name: ohyeahpaulchin
favicon: null
layout_spectrum: 0.0107
typography_spectrum: 0.8972
title: Paul Chin
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02121a'
    - '#faf7f2'
    - '#b1b4ad'
    - '#808a8b'
    - '#7c605d'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
