name: ohyeahpaulchin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.689471716992557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#02121a'
    - '#faf7f2'
    - '#b1b4ad'
    - '#808a8b'
    - '#7c605d'
  brandStrength: 0.6875
  lightness: 0.8821355712134391
  saturation: 0.09410054562613368
  rhythmicContrast: 0.9162053959444165
purpose: []
