name: ohyeahpaulchin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.689471716992557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6333079584874213
  lightness: 0.8821355712134391
  saturation: 0.09410054562613368
  rhythmicContrast: 0.9162053959444165
purpose: []
