title: Paul Chin
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.4255319
favicon: null
name: ohyeahpaulchin
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.6875
  saturation: 0.1875
  brandColors:
    - '#02121a'
    - '#faf7f2'
    - '#b1b4ad'
    - '#808a8b'
    - '#7c605d'
  lightness: 0.625
  rhythmicContrast: 0.5
typography_spectrum: 0.7829787
