name: ohyeahpaulchin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.689471716992557
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d6d1'
    - '#76acac'
    - '#121c1e'
    - '#6a7064'
    - '#bc8e76'
  brandStrength: 0.6875
  lightness: 0.8821355712134391
  saturation: 0.09410054562613368
  rhythmicContrast: 0.9162053959444165
purpose: []
